package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Client;

public interface ClientDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	int deleteByPrimaryKey(Integer idClient);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	void insert(Client record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	void insertSelective(Client record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	Client selectByPrimaryKey(Integer idClient);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	int updateByPrimaryKeySelective(Client record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	int updateByPrimaryKey(Client record);
}