package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Entreprise;

public interface EntrepriseDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	int deleteByPrimaryKey(Integer idEntreprise);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	void insert(Entreprise record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	void insertSelective(Entreprise record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	Entreprise selectByPrimaryKey(Integer idEntreprise);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	int updateByPrimaryKeySelective(Entreprise record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	int updateByPrimaryKey(Entreprise record);
}