package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Grade;

public interface GradeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int deleteByPrimaryKey(Integer idGrade);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	void insert(Grade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	void insertSelective(Grade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	Grade selectByPrimaryKey(Integer idGrade);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int updateByPrimaryKeySelective(Grade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int updateByPrimaryKey(Grade record);
}