package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Historiquegrade;

public interface HistoriquegradeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int deleteByPrimaryKey(Integer idGrade, String matricule);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	void insert(Historiquegrade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	void insertSelective(Historiquegrade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	Historiquegrade selectByPrimaryKey(Integer idGrade, String matricule);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int updateByPrimaryKeySelective(Historiquegrade record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	int updateByPrimaryKey(Historiquegrade record);
}