package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Historiquepf;

public interface HistoriquepfDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	int deleteByPrimaryKey(Integer numAction, Integer numPf);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	void insert(Historiquepf record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	void insertSelective(Historiquepf record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	Historiquepf selectByPrimaryKey(Integer numAction, Integer numPf);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	int updateByPrimaryKeySelective(Historiquepf record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	int updateByPrimaryKey(Historiquepf record);
}