package com.NetTrading.server.ibatis.dao;

import com.NetTrading.server.ibatis.model.Ordre;

public interface OrdreDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	int deleteByPrimaryKey(Integer numOrdre);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	void insert(Ordre record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	void insertSelective(Ordre record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	Ordre selectByPrimaryKey(Integer numOrdre);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	int updateByPrimaryKeySelective(Ordre record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ordre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	int updateByPrimaryKey(Ordre record);
}