package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.ActionDAO;
import com.NetTrading.server.ibatis.model.Action;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ActionDAOImpl extends SqlMapClientDaoSupport implements ActionDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public ActionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public int deleteByPrimaryKey(Integer numAction) {
		Action key = new Action();
		key.setNumAction(numAction);
		int rows = getSqlMapClientTemplate().delete(
				"action.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void insert(Action record) {
		getSqlMapClientTemplate().insert("action.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void insertSelective(Action record) {
		getSqlMapClientTemplate().insert(
				"action.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public Action selectByPrimaryKey(Integer numAction) {
		Action key = new Action();
		key.setNumAction(numAction);
		Action record = (Action) getSqlMapClientTemplate().queryForObject(
				"action.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public int updateByPrimaryKeySelective(Action record) {
		int rows = getSqlMapClientTemplate().update(
				"action.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table action
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public int updateByPrimaryKey(Action record) {
		int rows = getSqlMapClientTemplate().update(
				"action.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
	public List<Action>getAll(){
    	
    	return (List<Action>)getSqlMapClientTemplate().queryForList("action.getAll");
    }
}