package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.AdministrateurDAO;

import com.NetTrading.server.ibatis.model.Administrateur;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AdministrateurDAOImpl extends SqlMapClientDaoSupport implements AdministrateurDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public AdministrateurDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int deleteByPrimaryKey(Integer id_admin) {
		Administrateur key = new Administrateur();
		key.setId_admin(id_admin);
		int rows = getSqlMapClientTemplate().delete(
				"administrateur.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insert(Administrateur record) {
		getSqlMapClientTemplate().insert(
				"administrateur.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insertSelective(Administrateur record) {
		getSqlMapClientTemplate().insert(
				"administrateur.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Administrateur selectByPrimaryKey(Integer id_admin) {
		Administrateur key = new Administrateur();
		key.setId_admin(id_admin);
		Administrateur record = (Administrateur) getSqlMapClientTemplate()
				.queryForObject(
						"administrateur.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKeySelective(Administrateur record) {
		int rows = getSqlMapClientTemplate().update(
				"administrateur.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table administrateur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKey(Administrateur record) {
		int rows = getSqlMapClientTemplate().update(
				"administrateur.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	public Administrateur isExist(String login,String pwd){
		Administrateur admi =new Administrateur();
		admi.setLogin(login);
		admi.setPassword(pwd);
		
		return (Administrateur)getSqlMapClientTemplate().queryForObject("administrateur.isExist",admi);
		
	}
	public Administrateur isExiste(String email){
		Administrateur admi =new Administrateur();
		admi.setEmail(email);
		
		
		return (Administrateur)getSqlMapClientTemplate().queryForObject("administrateur.isExiste",admi);
		
	}
	@SuppressWarnings("unchecked")
public List<Administrateur>getAll(){
    	
    	return (List<Administrateur>)getSqlMapClientTemplate().queryForList("administrateur.getAll");
    }

}