package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.ClientDAO;
import com.NetTrading.server.ibatis.model.Client;



import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ClientDAOImpl extends SqlMapClientDaoSupport implements ClientDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public ClientDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public int deleteByPrimaryKey(Integer idClient) {
		Client key = new Client();
		key.setIdClient(idClient);
		int rows = getSqlMapClientTemplate().delete(
				"client.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void insert(Client record) {
		getSqlMapClientTemplate().insert("client.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void insertSelective(Client record) {
		getSqlMapClientTemplate().insert(
				"client.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public Client selectByPrimaryKey(Integer idClient) {
		Client key = new Client();
		key.setIdClient(idClient);
		Client record = (Client) getSqlMapClientTemplate().queryForObject(
				"client.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public int updateByPrimaryKeySelective(Client record) {
		int rows = getSqlMapClientTemplate().update(
				"client.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table client
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public int updateByPrimaryKey(Client record) {
		int rows = getSqlMapClientTemplate().update(
				"client.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	public Client isExist(String login,String pwd){
    	Client client =new Client();
		client.setLogin(login);
		client.setPassword(pwd);
		
		return (Client)getSqlMapClientTemplate().queryForObject("client.isExist",client);
		
	}
	
	public Client isExiste(String email){
		Client client =new Client();
		client.setEmail(email);
		
		
		return (Client)getSqlMapClientTemplate().queryForObject("client.isExiste",client);
		
	}
	
	@SuppressWarnings("unchecked")
public List<Client>getAll(){
    	
    	return (List<Client>)getSqlMapClientTemplate().queryForList("client.getAll");
    }
}