package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.EntrepriseDAO;
import com.NetTrading.server.ibatis.model.Entreprise;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EntrepriseDAOImpl extends SqlMapClientDaoSupport implements EntrepriseDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public EntrepriseDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public int deleteByPrimaryKey(Integer idEntreprise) {
		Entreprise key = new Entreprise();
		key.setIdEntreprise(idEntreprise);
		int rows = getSqlMapClientTemplate().delete(
				"entreprise.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void insert(Entreprise record) {
		getSqlMapClientTemplate().insert("entreprise.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void insertSelective(Entreprise record) {
		getSqlMapClientTemplate().insert(
				"entreprise.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public Entreprise selectByPrimaryKey(Integer idEntreprise) {
		Entreprise key = new Entreprise();
		key.setIdEntreprise(idEntreprise);
		Entreprise record = (Entreprise) getSqlMapClientTemplate()
				.queryForObject(
						"entreprise.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public int updateByPrimaryKeySelective(Entreprise record) {
		int rows = getSqlMapClientTemplate().update(
				"entreprise.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table entreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public int updateByPrimaryKey(Entreprise record) {
		int rows = getSqlMapClientTemplate().update(
				"entreprise.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}
	@SuppressWarnings("unchecked")
public List<Entreprise>getAll(){
    	
    	return (List<Entreprise>)getSqlMapClientTemplate().queryForList("entreprise.getAll");
    }
}