package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.GradeDAO;

import com.NetTrading.server.ibatis.model.Grade;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GradeDAOImpl extends SqlMapClientDaoSupport implements GradeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public GradeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int deleteByPrimaryKey(Integer idGrade) {
		Grade key = new Grade();
		key.setIdGrade(idGrade);
		int rows = getSqlMapClientTemplate().delete(
				"grade.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insert(Grade record) {
		getSqlMapClientTemplate()
				.insert("grade.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insertSelective(Grade record) {
		getSqlMapClientTemplate().insert(
				"grade.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Grade selectByPrimaryKey(Integer idGrade) {
		Grade key = new Grade();
		key.setIdGrade(idGrade);
		Grade record = (Grade) getSqlMapClientTemplate().queryForObject(
				"grade.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKeySelective(Grade record) {
		int rows = getSqlMapClientTemplate().update(
				"grade.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table grade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKey(Grade record) {
		int rows = getSqlMapClientTemplate().update(
				"grade.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}
	@SuppressWarnings("unchecked")
public List<Grade>getAll(){
    	
    	return (List<Grade>)getSqlMapClientTemplate().queryForList("grade.getAll");
    }
}