package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.HistactionDAO;
import com.NetTrading.server.ibatis.model.Histaction;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HistactionDAOImpl extends SqlMapClientDaoSupport implements HistactionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public HistactionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int deleteByPrimaryKey(Integer idHistact) {
		Histaction key = new Histaction();
		key.setIdHistact(idHistact);
		int rows = getSqlMapClientTemplate().delete(
				"histaction.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insert(Histaction record) {
		getSqlMapClientTemplate().insert("histaction.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insertSelective(Histaction record) {
		getSqlMapClientTemplate().insert(
				"histaction.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Histaction selectByPrimaryKey(Integer idHistact) {
		Histaction key = new Histaction();
		key.setIdHistact(idHistact);
		Histaction record = (Histaction) getSqlMapClientTemplate()
				.queryForObject(
						"histaction.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKeySelective(Histaction record) {
		int rows = getSqlMapClientTemplate().update(
				"histaction.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table histaction
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKey(Histaction record) {
		int rows = getSqlMapClientTemplate().update(
				"histaction.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}
	@SuppressWarnings("unchecked")
public List<Histaction>getAll(){
    	
    	return (List<Histaction>)getSqlMapClientTemplate().queryForList("histaction.getAll");
    }
}