package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.HistoriquepfDAO;
import com.NetTrading.server.ibatis.model.HistPorTwo;
import com.NetTrading.server.ibatis.model.Historiquepf;
import com.NetTrading.server.ibatis.model.Portefeuille;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HistoriquepfDAOImpl extends SqlMapClientDaoSupport implements HistoriquepfDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public HistoriquepfDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int deleteByPrimaryKey(Integer numAction, Integer numPf) {
		Historiquepf key = new Historiquepf();
		key.setNumAction(numAction);
		key.setNumPf(numPf);
		int rows = getSqlMapClientTemplate().delete(
				"historiquepf.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void insert(Historiquepf record) {
		getSqlMapClientTemplate().insert("historiquepf.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void insertSelective(Historiquepf record) {
		getSqlMapClientTemplate().insert(
				"historiquepf.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Historiquepf selectByPrimaryKey(Integer numAction, Integer numPf) {
		Historiquepf key = new Historiquepf();
		key.setNumAction(numAction);
		key.setNumPf(numPf);
		Historiquepf record = (Historiquepf) getSqlMapClientTemplate()
				.queryForObject(
						"historiquepf.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int updateByPrimaryKeySelective(Historiquepf record) {
		int rows = getSqlMapClientTemplate().update(
				"historiquepf.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquepf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int updateByPrimaryKey(Historiquepf record) {
		int rows = getSqlMapClientTemplate().update(
				"historiquepf.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	@SuppressWarnings("unchecked")
public List<Historiquepf>getAll(){
    	
    	return (List<Historiquepf>)getSqlMapClientTemplate().queryForList("historiquepf.getAll");
    }
public List<HistPorTwo>getPortfeuilleActions(Historiquepf pf ){
	
    	
    	return (List<HistPorTwo>)getSqlMapClientTemplate().queryForList("historiquepf.getPortfeuilleActions",pf);
    }
	
}