package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.HistoriquegradeDAO;

import com.NetTrading.server.ibatis.model.Historiquegrade;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HistoriquegradeDAOImpl extends SqlMapClientDaoSupport implements HistoriquegradeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public HistoriquegradeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int deleteByPrimaryKey(Integer idGrade, String matricule) {
		Historiquegrade key = new Historiquegrade();
		key.setIdGrade(idGrade);
		key.setMatricule(matricule);
		int rows = getSqlMapClientTemplate().delete(
				"historiquegrade.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insert(Historiquegrade record) {
		getSqlMapClientTemplate().insert(
				"historiquegrade.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void insertSelective(Historiquegrade record) {
		getSqlMapClientTemplate().insert(
				"historiquegrade.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Historiquegrade selectByPrimaryKey(Integer idGrade, String matricule) {
		Historiquegrade key = new Historiquegrade();
		key.setIdGrade(idGrade);
		key.setMatricule(matricule);
		Historiquegrade record = (Historiquegrade) getSqlMapClientTemplate()
				.queryForObject(
						"historiquegrade.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKeySelective(Historiquegrade record) {
		int rows = getSqlMapClientTemplate().update(
				"historiquegrade.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table historiquegrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public int updateByPrimaryKey(Historiquegrade record) {
		int rows = getSqlMapClientTemplate().update(
				"historiquegrade.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}
	@SuppressWarnings("unchecked")
public List<Historiquegrade>getAll(){
    	
    	return (List<Historiquegrade>)getSqlMapClientTemplate().queryForList("historiquegrade.getAll");
    }
}