package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.PortefeuilleDAO;
import com.NetTrading.server.ibatis.model.Portefeuille;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public  class PortefeuilleDAOImpl extends SqlMapClientDaoSupport implements PortefeuilleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public PortefeuilleDAOImpl() {
		super();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int deleteByPrimaryKey(Integer numPf) {
		Portefeuille key = new Portefeuille();
		key.setNumPf(numPf);
		int rows = getSqlMapClientTemplate().delete(
				"portefeuille.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void insert(Portefeuille record) {
		getSqlMapClientTemplate().insert("portefeuille.ibatorgenerated_insert",
				record);
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void insertSelective(Portefeuille record) {
		getSqlMapClientTemplate().insert(
				"portefeuille.ibatorgenerated_insertSelective", record);
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Portefeuille selectByPrimaryKey(Integer numPf) {
		Portefeuille key = new Portefeuille();
		key.setNumPf(numPf);
		Portefeuille record = (Portefeuille) getSqlMapClientTemplate()
				.queryForObject(
						"portefeuille.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int updateByPrimaryKeySelective(Portefeuille record) {
		int rows = getSqlMapClientTemplate().update(
				"portefeuille.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table portefeuille
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public int updateByPrimaryKey(Portefeuille record) {
		int rows = getSqlMapClientTemplate().update(
				"portefeuille.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}


	@SuppressWarnings("unchecked")
	
public List<Portefeuille>getAll(int id){
		Portefeuille e=new  Portefeuille();
		e.setNumPf(id);
    	
    	return (List<Portefeuille>)getSqlMapClientTemplate().queryForList("portefeuille.getAll");
    }


public   Portefeuille getByNumClient(int id){
	Portefeuille pf=new  Portefeuille();
	pf.setIdClient(id);
	
	return (Portefeuille)getSqlMapClientTemplate().queryForObject("portefeuille.getByNumClient",pf);
}
}