package com.NetTrading.server.ibatis.daoImpl;

import java.util.List;

import com.NetTrading.server.ibatis.dao.TraderDAO;

import com.NetTrading.server.ibatis.model.Trader;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TraderDAOImpl extends SqlMapClientDaoSupport implements TraderDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public TraderDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public int deleteByPrimaryKey(String matricule) {
		Trader key = new Trader();
		key.setMatricule(matricule);
		int rows = getSqlMapClientTemplate().delete(
				"trader.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void insert(Trader record) {
		getSqlMapClientTemplate().insert("trader.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void insertSelective(Trader record) {
		getSqlMapClientTemplate().insert(
				"trader.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public Trader selectByPrimaryKey(String matricule) {
		Trader key = new Trader();
		key.setMatricule(matricule);
		Trader record = (Trader) getSqlMapClientTemplate().queryForObject(
				"trader.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public int updateByPrimaryKeySelective(Trader record) {
		int rows = getSqlMapClientTemplate().update(
				"trader.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public int updateByPrimaryKey(Trader record) {
		int rows = getSqlMapClientTemplate().update(
				"trader.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	public Trader isExist(String login,String pwd){
    	Trader trader =new Trader();
    	trader.setLogin(login);
    	trader.setPassword(pwd);
		
		return (Trader)getSqlMapClientTemplate().queryForObject("trader.isExist",trader);
		
	}
	
	public Trader isExiste(String email){
		Trader trader =new Trader();
		trader.setEmail(email);
		
		
		return (Trader)getSqlMapClientTemplate().queryForObject("client.isExiste",trader);
		
	}
	@SuppressWarnings("unchecked")
public List<Trader>getAll(){
    	
    	return (List<Trader>)getSqlMapClientTemplate().queryForList("trader.getAll");
    }
	
	
	


}