package com.NetTrading.server.ibatis.model;

import java.util.Date;

public class Action {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.numAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private Integer numAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.idEntreprise
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private Integer idEntreprise;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.prixAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private Integer prixAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.dateEmis
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private Date dateEmis;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.NomAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private String nomAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column action.Categorie
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	private String categorie;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.numAction
	 * @return  the value of action.numAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public Integer getNumAction() {
		return numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.numAction
	 * @param numAction  the value for action.numAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setNumAction(Integer numAction) {
		this.numAction = numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.idEntreprise
	 * @return  the value of action.idEntreprise
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public Integer getIdEntreprise() {
		return idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.idEntreprise
	 * @param idEntreprise  the value for action.idEntreprise
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setIdEntreprise(Integer idEntreprise) {
		this.idEntreprise = idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.prixAction
	 * @return  the value of action.prixAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public Integer getPrixAction() {
		return prixAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.prixAction
	 * @param prixAction  the value for action.prixAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setPrixAction(Integer prixAction) {
		this.prixAction = prixAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.dateEmis
	 * @return  the value of action.dateEmis
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public Date getDateEmis() {
		return dateEmis;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.dateEmis
	 * @param dateEmis  the value for action.dateEmis
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setDateEmis(Date dateEmis) {
		this.dateEmis = dateEmis;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.NomAction
	 * @return  the value of action.NomAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public String getNomAction() {
		return nomAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.NomAction
	 * @param nomAction  the value for action.NomAction
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setNomAction(String nomAction) {
		this.nomAction = nomAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column action.Categorie
	 * @return  the value of action.Categorie
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public String getCategorie() {
		return categorie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column action.Categorie
	 * @param categorie  the value for action.Categorie
	 * @ibatorgenerated  Thu Jan 17 14:20:22 CET 2013
	 */
	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}
}