package com.NetTrading.server.ibatis.model;

public class Administrateur {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column administrateur.Id_admin
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Integer id_admin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column administrateur.login
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private String login;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column administrateur.password
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column administrateur.email
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private String email;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column administrateur.Id_admin
	 * @return  the value of administrateur.Id_admin
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Integer getId_admin() {
		return id_admin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column administrateur.Id_admin
	 * @param id_admin  the value for administrateur.Id_admin
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setId_admin(Integer id_admin) {
		this.id_admin = id_admin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column administrateur.login
	 * @return  the value of administrateur.login
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column administrateur.login
	 * @param login  the value for administrateur.login
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column administrateur.password
	 * @return  the value of administrateur.password
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column administrateur.password
	 * @param password  the value for administrateur.password
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column administrateur.email
	 * @return  the value of administrateur.email
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column administrateur.email
	 * @param email  the value for administrateur.email
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}