package com.NetTrading.server.ibatis.model;

public class Client {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.idClient
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private Integer idClient;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.login
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String login;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.password
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.matricule
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String matricule;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.idEntreprise
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private Integer idEntreprise;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.numAction
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private Integer numAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.numPf
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private Integer numPf;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.nom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String nom;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.prenom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String prenom;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.adresse
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String adresse;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.tel
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String tel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.email
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column client.profession
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	private String profession;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.idClient
	 * @return  the value of client.idClient
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public Integer getIdClient() {
		return idClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.idClient
	 * @param idClient  the value for client.idClient
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.login
	 * @return  the value of client.login
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.login
	 * @param login  the value for client.login
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.password
	 * @return  the value of client.password
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.password
	 * @param password  the value for client.password
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.matricule
	 * @return  the value of client.matricule
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getMatricule() {
		return matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.matricule
	 * @param matricule  the value for client.matricule
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.idEntreprise
	 * @return  the value of client.idEntreprise
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public Integer getIdEntreprise() {
		return idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.idEntreprise
	 * @param idEntreprise  the value for client.idEntreprise
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setIdEntreprise(Integer idEntreprise) {
		this.idEntreprise = idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.numAction
	 * @return  the value of client.numAction
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public Integer getNumAction() {
		return numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.numAction
	 * @param numAction  the value for client.numAction
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setNumAction(Integer numAction) {
		this.numAction = numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.numPf
	 * @return  the value of client.numPf
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public Integer getNumPf() {
		return numPf;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.numPf
	 * @param numPf  the value for client.numPf
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setNumPf(Integer numPf) {
		this.numPf = numPf;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.nom
	 * @return  the value of client.nom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getNom() {
		return nom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.nom
	 * @param nom  the value for client.nom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setNom(String nom) {
		this.nom = nom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.prenom
	 * @return  the value of client.prenom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getPrenom() {
		return prenom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.prenom
	 * @param prenom  the value for client.prenom
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.adresse
	 * @return  the value of client.adresse
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getAdresse() {
		return adresse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.adresse
	 * @param adresse  the value for client.adresse
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.tel
	 * @return  the value of client.tel
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.tel
	 * @param tel  the value for client.tel
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.email
	 * @return  the value of client.email
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.email
	 * @param email  the value for client.email
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column client.profession
	 * @return  the value of client.profession
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public String getProfession() {
		return profession;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column client.profession
	 * @param profession  the value for client.profession
	 * @ibatorgenerated  Mon Jan 14 23:41:14 CET 2013
	 */
	public void setProfession(String profession) {
		this.profession = profession;
	}
}