package com.NetTrading.server.ibatis.model;

public class Entreprise {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column entreprise.idEntreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	private Integer idEntreprise;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column entreprise.nom
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	private String nom;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column entreprise.adresse
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	private String adresse;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column entreprise.tel
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	private String tel;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column entreprise.idEntreprise
	 * @return  the value of entreprise.idEntreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public Integer getIdEntreprise() {
		return idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column entreprise.idEntreprise
	 * @param idEntreprise  the value for entreprise.idEntreprise
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void setIdEntreprise(Integer idEntreprise) {
		this.idEntreprise = idEntreprise;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column entreprise.nom
	 * @return  the value of entreprise.nom
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public String getNom() {
		return nom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column entreprise.nom
	 * @param nom  the value for entreprise.nom
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void setNom(String nom) {
		this.nom = nom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column entreprise.adresse
	 * @return  the value of entreprise.adresse
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public String getAdresse() {
		return adresse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column entreprise.adresse
	 * @param adresse  the value for entreprise.adresse
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column entreprise.tel
	 * @return  the value of entreprise.tel
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column entreprise.tel
	 * @param tel  the value for entreprise.tel
	 * @ibatorgenerated  Tue Jan 15 12:27:06 CET 2013
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}
}