package com.NetTrading.server.ibatis.model;

public class Grade {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column grade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Integer idGrade;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column grade.valeur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private String valeur;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column grade.ordreGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Integer ordreGrade;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column grade.idGrade
	 * @return  the value of grade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Integer getIdGrade() {
		return idGrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column grade.idGrade
	 * @param idGrade  the value for grade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setIdGrade(Integer idGrade) {
		this.idGrade = idGrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column grade.valeur
	 * @return  the value of grade.valeur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public String getValeur() {
		return valeur;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column grade.valeur
	 * @param valeur  the value for grade.valeur
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column grade.ordreGrade
	 * @return  the value of grade.ordreGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Integer getOrdreGrade() {
		return ordreGrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column grade.ordreGrade
	 * @param ordreGrade  the value for grade.ordreGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setOrdreGrade(Integer ordreGrade) {
		this.ordreGrade = ordreGrade;
	}
}