package com.NetTrading.server.ibatis.model;

import java.util.Date;

public class Historiquegrade {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquegrade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Integer idGrade;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquegrade.matricule
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private String matricule;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquegrade.dateEntree
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Date dateEntree;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquegrade.dateSortie
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	private Date dateSortie;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquegrade.idGrade
	 * @return  the value of historiquegrade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Integer getIdGrade() {
		return idGrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquegrade.idGrade
	 * @param idGrade  the value for historiquegrade.idGrade
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setIdGrade(Integer idGrade) {
		this.idGrade = idGrade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquegrade.matricule
	 * @return  the value of historiquegrade.matricule
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public String getMatricule() {
		return matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquegrade.matricule
	 * @param matricule  the value for historiquegrade.matricule
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquegrade.dateEntree
	 * @return  the value of historiquegrade.dateEntree
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Date getDateEntree() {
		return dateEntree;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquegrade.dateEntree
	 * @param dateEntree  the value for historiquegrade.dateEntree
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setDateEntree(Date dateEntree) {
		this.dateEntree = dateEntree;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquegrade.dateSortie
	 * @return  the value of historiquegrade.dateSortie
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public Date getDateSortie() {
		return dateSortie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquegrade.dateSortie
	 * @param dateSortie  the value for historiquegrade.dateSortie
	 * @ibatorgenerated  Mon Jan 14 17:44:12 CET 2013
	 */
	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}
}