package com.NetTrading.server.ibatis.model;

import java.util.Date;

public class Historiquepf {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquepf.numAction
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	private Integer numAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquepf.numPf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	private Integer numPf;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquepf.Dentre
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	private Date dentre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquepf.Dsortie
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	private Date dsortie;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column historiquepf.Quantite
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	private Integer quantite;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquepf.numAction
	 * @return  the value of historiquepf.numAction
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Integer getNumAction() {
		return numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquepf.numAction
	 * @param numAction  the value for historiquepf.numAction
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void setNumAction(Integer numAction) {
		this.numAction = numAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquepf.numPf
	 * @return  the value of historiquepf.numPf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Integer getNumPf() {
		return numPf;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquepf.numPf
	 * @param numPf  the value for historiquepf.numPf
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void setNumPf(Integer numPf) {
		this.numPf = numPf;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquepf.Dentre
	 * @return  the value of historiquepf.Dentre
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Date getDentre() {
		return dentre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquepf.Dentre
	 * @param dentre  the value for historiquepf.Dentre
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void setDentre(Date dentre) {
		this.dentre = dentre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquepf.Dsortie
	 * @return  the value of historiquepf.Dsortie
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Date getDsortie() {
		return dsortie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquepf.Dsortie
	 * @param dsortie  the value for historiquepf.Dsortie
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void setDsortie(Date dsortie) {
		this.dsortie = dsortie;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column historiquepf.Quantite
	 * @return  the value of historiquepf.Quantite
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public Integer getQuantite() {
		return quantite;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column historiquepf.Quantite
	 * @param quantite  the value for historiquepf.Quantite
	 * @ibatorgenerated  Tue Jan 22 16:59:55 CET 2013
	 */
	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}
}