package com.NetTrading.server.ibatis.model;

import java.util.Date;

public class Ordre {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.numOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Integer numOrdre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.idClient
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Integer idClient;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.dateOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Date dateOrdre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.etat
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private String etat;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.dateExec
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Date dateExec;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.nbAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Integer nbAction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.typeOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private String typeOrdre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column ordre.idAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	private Integer idAction;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.numOrdre
	 * @return  the value of ordre.numOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Integer getNumOrdre() {
		return numOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.numOrdre
	 * @param numOrdre  the value for ordre.numOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setNumOrdre(Integer numOrdre) {
		this.numOrdre = numOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.idClient
	 * @return  the value of ordre.idClient
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Integer getIdClient() {
		return idClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.idClient
	 * @param idClient  the value for ordre.idClient
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.dateOrdre
	 * @return  the value of ordre.dateOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Date getDateOrdre() {
		return dateOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.dateOrdre
	 * @param dateOrdre  the value for ordre.dateOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setDateOrdre(Date dateOrdre) {
		this.dateOrdre = dateOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.etat
	 * @return  the value of ordre.etat
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public String getEtat() {
		return etat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.etat
	 * @param etat  the value for ordre.etat
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setEtat(String etat) {
		this.etat = etat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.dateExec
	 * @return  the value of ordre.dateExec
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Date getDateExec() {
		return dateExec;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.dateExec
	 * @param dateExec  the value for ordre.dateExec
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setDateExec(Date dateExec) {
		this.dateExec = dateExec;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.nbAction
	 * @return  the value of ordre.nbAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Integer getNbAction() {
		return nbAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.nbAction
	 * @param nbAction  the value for ordre.nbAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setNbAction(Integer nbAction) {
		this.nbAction = nbAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.typeOrdre
	 * @return  the value of ordre.typeOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public String getTypeOrdre() {
		return typeOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.typeOrdre
	 * @param typeOrdre  the value for ordre.typeOrdre
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setTypeOrdre(String typeOrdre) {
		this.typeOrdre = typeOrdre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column ordre.idAction
	 * @return  the value of ordre.idAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public Integer getIdAction() {
		return idAction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column ordre.idAction
	 * @param idAction  the value for ordre.idAction
	 * @ibatorgenerated  Wed Jan 23 17:31:43 CET 2013
	 */
	public void setIdAction(Integer idAction) {
		this.idAction = idAction;
	}
}