package com.NetTrading.server.ibatis.model;

import java.util.Date;

public class Trader {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.matricule
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String matricule;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.login
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String login;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.password
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.nomTrader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String nomTrader;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.prenomTarder
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String prenomTarder;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.numPoste
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private Integer numPoste;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.dateRecrutement
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private Date dateRecrutement;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.email
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column trader.etat
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	private String etat;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.matricule
	 * @return  the value of trader.matricule
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getMatricule() {
		return matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.matricule
	 * @param matricule  the value for trader.matricule
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.login
	 * @return  the value of trader.login
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.login
	 * @param login  the value for trader.login
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.password
	 * @return  the value of trader.password
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.password
	 * @param password  the value for trader.password
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.nomTrader
	 * @return  the value of trader.nomTrader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getNomTrader() {
		return nomTrader;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.nomTrader
	 * @param nomTrader  the value for trader.nomTrader
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setNomTrader(String nomTrader) {
		this.nomTrader = nomTrader;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.prenomTarder
	 * @return  the value of trader.prenomTarder
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getPrenomTarder() {
		return prenomTarder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.prenomTarder
	 * @param prenomTarder  the value for trader.prenomTarder
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setPrenomTarder(String prenomTarder) {
		this.prenomTarder = prenomTarder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.numPoste
	 * @return  the value of trader.numPoste
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public Integer getNumPoste() {
		return numPoste;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.numPoste
	 * @param numPoste  the value for trader.numPoste
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setNumPoste(Integer numPoste) {
		this.numPoste = numPoste;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.dateRecrutement
	 * @return  the value of trader.dateRecrutement
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public Date getDateRecrutement() {
		return dateRecrutement;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.dateRecrutement
	 * @param dateRecrutement  the value for trader.dateRecrutement
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setDateRecrutement(Date dateRecrutement) {
		this.dateRecrutement = dateRecrutement;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.email
	 * @return  the value of trader.email
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.email
	 * @param email  the value for trader.email
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column trader.etat
	 * @return  the value of trader.etat
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public String getEtat() {
		return etat;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column trader.etat
	 * @param etat  the value for trader.etat
	 * @ibatorgenerated  Wed Jan 23 11:22:10 CET 2013
	 */
	public void setEtat(String etat) {
		this.etat = etat;
	}
}